version: '3.8'

services:
  infra-test:
    build:
      context: .
      dockerfile: flask.Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_KEY: ${FLASK_KEY}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_SECRET_ID: ${SPOTIFY_SECRET_ID}
      ENVIRONMENT: ${ENVIRONMENT}
      MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      EC2_dbs_IP: ${EC2_dbs_IP}
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: database.Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
